### ISSUE TITLE
Table interior out-shouts the redesigned panel frame

### ISSUE THREAD

**Issue by mortik** [fleetyards/fleetyards#4369]
The Panel redesign (#4362) changes the table *frame* for free at 36 production sites — `BaseTable` composes `Panel`, so it picks up the new surface, 2px edge, 16px radius and end-caps. The table's **interior** was deliberately left out of that PR's scope, and it now out-shouts the quieter frame around it.

## What's mismatched

**The row hover rail** — `app/frontend/shared/components/base/Table/Col/index.scss:9-26` and `:32-49`

A 4px `$primary` rail on the first and last cell of a hovered row, each carrying a triple glow:

```scss
box-shadow:
  3px 0 10px rgba(darken($primary, 20%), 0.9),
  0 3px 10px rgba(darken($primary, 20%), 0.9),
  0 -3px 10px rgba(darken($primary, 20%), 0.9);
```

Three 10px shadows at 0.9 alpha is the loudest thing on the page next to a frame whose whole premise is restraint. Worth noting the rail is already 4px — the same width as the new panel cap (`--cap-h`), so it could reuse that language rather than fight it: the cap says "this is a surface" in `#7a8288`, and the rail could say "this row" the same way instead of with a primary-blue bloom.

**The header rule** — `Table/Col/index.scss:95`

```scss
th.base-table-col {
  border-bottom: 1px solid $gray;
}
```

A solid `$gray` hairline under the header, where the redesign uses `--color-edge-soft` (`rgb(122 130 136 / 0.28)`) for internal divisions — the same call the dropdown menu separator now makes.

## Scope

Two rules, no markup change and no component rewrite. Explicitly *not* a full table-interior redesign — header typography, row density and cell alignment are all fine as they are and out of scope here.

## Why it wasn't done in #4362

That PR is already 118 files and has been bounced twice by the review bot's file limit. It carries two component rewrites (`StatsPanel` and `MetricsCard`, both now Panel compositions); a third would have made it harder to review for no gain in correctness. The mismatch is real and it is #4362's to own — hence this issue rather than nothing.

`BaseTable2` is not in scope: it reaches no user (4 call sites, all on the visual-tests page) and composes `Panel` directly, so it tracks the rebuild on its own. 🤖
