### PR TITLE
fix(hangar-import): every import fails on a column that was never written

### PR DESCRIPTION
**Pull request by mortik**
Every hangar import has been failing since #4866, immediately and with nothing imported:

> `undefined method 'size' for nil`

## Why

`Imports::HangarImport` parsed the uploaded file in an `after_create` callback, so `self.import_data = ...` ran after the INSERT and was never written. The column has been NULL for every hangar import ever created.

That stayed invisible while the run happened inline in the request. The controller held the same instance, its no-data guard read the in-memory value, and `HangarImporter#run` flushed the dirty attribute along with `start!` — which is why finished imports in production do have an `import_data`.

#4866 moved the run into `HangarImportJob`, which loads the row by id. It reads back a column that was always empty: the loop guards the nil with `|| []` and imports nothing, and `missing_models.size < @import.import_data.size` two lines later raises.

## What changed

- `before_create`, so the parsed file is part of the INSERT. The items are read once into a local, so there is no second read to disagree with the first.
- An item that carries a slug and no name imports instead of taking the run down with `undefined method 'gsub' for nil` — five imports in the history died that way, after partially building the user's hangar. The slug alone is enough to match on. An unmatched one is reported under its slug rather than under a nil that `missing.sort` would raise on, and an item that identifies nothing at all is skipped.
- `success` asks whether anything was imported, which is what `missing.size < items.size` meant only while every item landed in one list or the other.

## Testing

Every loader test ran the importer against the instance that created the import — the one state the job never sees. One of them loads the record by id now, and it reproduces the production error exactly on the old code:

```
ERROR HangarImporterTest#test_runs_against_a_record_loaded_fresh,_the_way_the_job_does
  NoMethodError: undefined method 'size' for nil
ERROR HangarImporterTest#test_imports_an_item_that_carries_only_a_slug
  NoMethodError: undefined method 'gsub' for nil
```

No migration, no schema change. Existing rows stay as they are — the ones worth re-running are the failures, and those need a fresh upload anyway.

🤖

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved import handling for blank, missing, or slug-only item details.
  * Preserved parsed import data for later processing.
  * Improved reporting for items that cannot be matched.
  * Imports now correctly fail when no models are imported or when cancelled during final processing.
* **Tests**
  * Added coverage for import persistence, identifier handling, unmatched items, empty results, and cancellation.

---

<a href="https://app.devin.ai/review/fleetyards/fleetyards/pull/5118" target="_blank"><picture><source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-devin-review-dark.svg?v=4">Devin Review</picture></a>

### CODE REVIEW

File: app/lib/hangar_importer.rb [hunk 1]
```diff
@@ -102,7 +108,9 @@ def run
           next
         end
 
-        missing_models << item[:name]
+        # A slug-only item has no name to report, and `missing` is sorted --
+        # one nil in the list raises rather than naming what went unmatched.
+        missing_models << (item[:name].presence || item[:slug])
```
[the remark this answers is not in the document]
Comment (mortik) [reply app/lib/hangar_importer.rb]: Good catch — fixed in 8133bf0.

`paint_slug` does clear the identifies-nothing guard, so the report had nothing left to name it by. Rather than chaining a third fallback, the miss is now reported under `slug` — the local the lookup actually bound, which already holds `paint_slug` where the item carried one. That also stops an item with both a `slug` and a `paint_slug` being reported under a slug that was never queried, and the guard above guarantees it is non-nil.

Regression test added: a paint-only miss beside a named one, which raised `comparison of NilClass with String` before. 🤖

File: app/lib/hangar_importer.rb [hunk 2]
```diff
@@ -113,7 +124,9 @@ def run
     output = {
       missing: missing_models.sort,
       imported: imported_models.sort,
-      success: !cancelled && missing_models.size < @import.import_data.size
+      # `missing_models.size < items.size` counted an item the run skipped as a
+      # success, so a file of nothing but unidentifiable entries reported one.
+      success: !cancelled && imported_models.any?
```
[the remark this answers is not in the document]
Comment (mortik) [reply app/lib/hangar_importer.rb:134]: Valid — fixed in 2f879c6. Pre-existing rather than introduced here (the old `missing.size < items.size` had the same gap), but the line was already being touched.

The cancellation state is read once now and shared by both uses, instead of the local flag deciding `success` and a separate `reload` deciding the transition:

```ruby
cancelled ||= @import.reload.cancelled?
...
success: !cancelled && imported_models.any?
...
@import.finish! unless cancelled
```

Regression test added: a cancellation that lands after the loop's last checkpoint, which reported `success: true` before. 🤖
